### ISSUE TITLE
crash after upgrading to 1.1.1

### ISSUE THREAD

**Issue by kols** [nomad/cupertino#149]
```
$ ios --trace
(erb):14:in `block in get_binding': undefined method `name' for nil:NilClass (NoMethodError)
        from (erb):13:in `each'
        from (erb):13:in `get_binding'
        from /Users/kane/.rbenv/versions/2.1.2/lib/ruby/2.1.0/erb.rb:850:in `eval'
        from /Users/kane/.rbenv/versions/2.1.2/lib/ruby/2.1.0/erb.rb:850:in `result'
        from /Users/kane/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.1.6/lib/commander/help_formatters/terminal.rb:8:in `render'
        from /Users/kane/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.1.6/lib/commander/runner.rb:295:in `block (2 levels) in create_default_commands'
        from /Users/kane/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.1.6/lib/commander/command.rb:180:in `call'
        from /Users/kane/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.1.6/lib/commander/command.rb:180:in `call'
        from /Users/kane/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.1.6/lib/commander/command.rb:155:in `run'
        from /Users/kane/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.1.6/lib/commander/runner.rb:422:in `run_active_command'
        from /Users/kane/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.1.6/lib/commander/runner.rb:82:in `run!'
        from /Users/kane/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.1.6/lib/commander/delegates.rb:8:in `run!'
        from /Users/kane/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/commander-4.1.6/lib/commander/import.rb:10:in `block in <top (required)>'
```
